# Main config file for Hugo site
# Ref: https://gohugo.io/getting-started/configuration/

baseURL = 'https://www.orthophoniechezsoi.ca/'
defaultContentLanguage = "fr"
languageCode = 'fr-ca'
title = 'Orthophonie chez soi'
subtitle = 'Mélodie Gagnon, orthophoniste, M.P.O.'
#description = ""
#keywords = ""
copyright = "&copy; 2021 -- {currentYear} Orthophonie chez soi --- Mélodie Gagnon, orthophoniste, M.P.O."

enableGitInfo = true
enableRobotsTXT = true
removePathAccents = true
disableKinds = [
  'RSS',
  'section',
  'taxonomy',  # categories & associated page
  'term',  # tags listing & associated page
]

### Themes
#theme = 'ananke'

# WARN  found no layout file for "amp" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
#theme = 'blox'

# Home page empty: refer to data/homepage.yml
theme = 'arcana'

# Strange...
#theme = 'alpha'

#dateFormatSingle = "2006-01-02"
#dateFormatList = "2006-01-02"
#lastModDisplay = "modified"


[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 3  # Page title is already h2.

### Menu:
[menus]
[[menus.main]]
  name = 'Accueil'
  pageRef = '/'
  weight = 10
[[menus.main]]
  name = 'À propos'
  pageRef = '/apropos'
  weight = 20
[[menus.main]]
  name = 'Services'
  pageRef = '/services'
  weight = 30
[[menus.main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 40
[[menus.main]]
  name = 'Confidentialité'
  pageRef = '/confidentialite'
  weight = 50

# Not working???
#[[menus.footer]]
#  name = 'Politique de confidentialité'
#  pageRef = '/politique-de-confidentialite'
#  weight = 10

[outputs]
  home = [
    'html',
    #'amp',
    #'json',
    ]
  page = [
    'html',
    #'amp',
    #'json',
    ]

[params]
  # Remove: "Design: HTML5 UP  Theme"
  attribution = false

  # Remove: opengraph tags
  opengraph = false

  #custom_css = ["/custom.css"]

  #[params.footer]
  #  [[params.footer.links]]
  #    header = "Links Section A"
  #  [[params.footer.links.links]]
  #    title = "Politique de confidentialité"
  #    url = "/politique-de-confidentialite"
  #  [[params.footer.links.links]]
  #    title = "Link 2a"
  #    url = "#"
  #  [[params.footer.links]]
  #    header = "Links Section B"
  #  [[params.footer.links.links]]
  #    title = "Link 1b"
  #    url = "#"
  #  [[params.footer.links]]
  #    header = "Links Section C"
  #  [[params.footer.links.links]]
  #    title = "Link 1c"
  #    url = "#"

    #[params.footer.contact_form]
    #  enabled = true
    #  header = "Contactez-nous"
    #  action = ""
    #  contact_name = "Nom"
    #  contact_email = "Courriel"
    #  contact_message = "Votre message"
    #  contact_submit = "Envoyer"

  #[[params.social]]
  #  title = "Twitter"
  #  icon = "fa-twitter"
  #  url = "#"
  #[[params.social]]
  #  title = "Facebook"
  #  icon = "fa-facebook-f"
  #  url = "#"
  #[[params.social]]
  #  title = "GitHub"
  #  icon = "fa-github"
  #  url = "#"
  #[[params.social]]
  #  title = "LinkedIn"
  #  icon = "fa-linkedin-in"
  #  url = "#"
  #[[params.social]]
  #  title = "Creative Commons"
  #  icon = "fa-creative-commons"
  #  url = "https://creativecommons.org/"
