# Main config file for Hugo site
# Ref: https://gohugo.io/getting-started/configuration/

baseURL = 'https://www.orthophoniechezsoi.ca/'
languageCode = 'fr-ca'
title = 'Orthophonie chez soi'

theme = 'ananke'
# theme = 'blox'
# theme = 'arcana'

copyright = 'Orthophonie chez soi — Mélodie Gagnon, orthophoniste, M.P.O. '
enableGitInfo = true
enableRobotsTXT = false
removePathAccents = true
disableKinds = ['RSS', 'section', 'taxonomy', 'term']

[outputs]
  home = ['html', 'amp']
  page = ['html', 'amp']
